name: Build GitHub Page Web

on:
  workflow_dispatch:
  push:
    branches:
      - Flutter

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - uses: subosito/flutter-action@v2
      #   with:
      #     channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
      # - run: flutter --version

      # - name: Enable Flutter Web
      #   run: flutter config --enable-web
      
      - name: Check folders
        run: |
          PWDPATH=$(pwd)
          ls -a
          cd /home/runner/work/Line-Converter/Line-Converter
          ls -a
          cd ./page
          ls -a 
          cat home.dart

      - name: Download Dependencies
        run: |
          pwd
          flutter clean
          flutter pub get
          
      - name: Build
        run: flutter build web --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false --release --base-href "/Line_Converter/" --web-renderer canvaskit

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.COMMIT_SERCRT }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
